requires 'Bio::DB::BigFile';
requires 'Bio::DB::HTS';
requires 'JSON';
requires 'Sereal';
requires 'Set::IntervalTree';
requires 'String::Approx';
requires 'XML::Hash::XS';
requires 'XML::LibXML::Reader';
requires 'Date::Manip::Date';
